### ISSUE TITLE
Custom model water + BTK animation not rendering properly

### ISSUE THREAD

**Issue by LagoLunatic** [Sage-of-Mirrors/J3DUltra#7]
Custom model made by BSZ with SuperBMD, and BTK animation made by [btk-conv](https://github.com/RenolY2/btk-conv):
[model.zip](https://github.com/user-attachments/files/17170568/model.zip)

It renders like this, and isn't being animated by the BTK (neither the waterfall nor the pond):
![image](https://github.com/user-attachments/assets/84523d3c-110b-439f-ba58-d700dfb5cc90)

It works ingame, it also works in noclip, where renders like this, and is animated by the BTK:
![image](https://github.com/user-attachments/assets/a5fd26b4-6d56-4d7f-acea-fba96a3d44c9)

Tested on latest main commit, with the only change being the bugfix in #6

**Comment by Sage-of-Mirrors** [comment]
I'll take a look at this in RenderDoc in a bit. Seems J3DUltra still has some bugs to sort out.

**Comment by Sage-of-Mirrors** [comment]
It appears to render correctly in my viewer program, Jekyll:
![image](https://github.com/user-attachments/assets/b0c60dc2-6a03-4fc3-828d-6508a1b63cd1)

Jekyll is using this sort algorithm: <https://github.com/Sage-of-Mirrors/Jekyll/blob/main/src/application/AJ3DContext.cpp#L34>. What does GCFT use?

**Comment by LagoLunatic** [comment]
PyJ3DUltra seems to use this simple sort function that doesn't distinguish between opaque and transparent materials:
https://github.com/LagoLunatic/PyJ3DUltra/blob/733abcd52adb72ef91d1fd1446f9fc32107fbde0/src/main.cpp#L38-L43

I copied your SortFuncTest into PyJ3DUltra, and it seems to fix the water not being blue issue.

However, there are two issues. First, loading the BTK still doesn't seem to animate the water, same as before.

Second, almost any transformation to the camera (rotating, zooming, translating) seems to mess up the rendering and make most of the model transparent, which didn't happen with the original sort function.
Here's an example, the first image is the default camera position, and the second is after rotating the camera by about 5 degrees or so:
![image](https://github.com/user-attachments/assets/844f4369-c5e4-451c-acce-c16433bdfeab)
![image](https://github.com/user-attachments/assets/791ed0c0-b585-4e44-9c79-548def6190b3)

Do either of these issues happen in Jekyll?

**Comment by Sage-of-Mirrors** [comment]
Hmm... you're right that BTK seems broken. I'll look into that.

The other issue doesn't happen. Here's the build of Jekyll I used:
[jekyll.zip](https://github.com/user-attachments/files/17171448/jekyll.zip)

You can just drag-and-drop the model file onto the viewport.

**Comment by Sage-of-Mirrors** [comment]
Looks like the materials for the water don't use a tex matrix transform to modify the UVs:
![image](https://github.com/user-attachments/assets/4c8881c3-503a-420b-90c7-61c4a1bd8a8a)

**Comment by LagoLunatic** [comment]
noclip's code has this comment in it:
https://github.com/magcius/noclip.website/blob/3832c0c84d3c54d1492f6ce0a2834480fd04377c/src/Common/JSYSTEM/J3D/J3DLoader.ts#L1157-L1163

**Comment by Sage-of-Mirrors** [comment]
Ah. I'll fix that then. Thank you for bringing it to my attention!

**Comment by Sage-of-Mirrors** [comment]
Try https://github.com/Sage-of-Mirrors/J3DUltra/commit/629e7a09f204231f069d2ee72259674ce333a52a and let me know if it's fixed!

**Comment by LagoLunatic** [comment]
Yep, animates perfectly now!

I'm still confused about the sort function breaking, so I made a PyJ3DUltra issue for it here: https://github.com/Astral-C/PyJ3DUltra/issues/4
